version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    command: gunicorn anygram.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
      - nginx_conf:/nginx/
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - web
