# Generated by Django 3.1.7 on 2021-03-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210313_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
