# Generated by Django 3.1.7 on 2021-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210320_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('badge badge_style_orange', 'Orange'), ('badge badge_style_green', 'Green'), ('badge badge_style_purple', 'Purple')], default='badge badge_style_purple', max_length=30, verbose_name='Выберите цвет тега'),
        ),
    ]
